//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CKS.Dev.Core.Cmd.Imp.v5.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CKS.Dev.Core.Cmd.Imp.v5.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content type {0} was not found in the available content types collection..
        /// </summary>
        internal static string ContentTypeSharePointCommands_GetContentTypeIDException {
            get {
                return ResourceManager.GetString("ContentTypeSharePointCommands_GetContentTypeIDException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content type {0} was not found in the available content types collection..
        /// </summary>
        internal static string ContentTypeSharePointCommands_GetContentTypePropertiesException {
            get {
                return ResourceManager.GetString("ContentTypeSharePointCommands_GetContentTypePropertiesException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following exception has occured while trying to parse the developer dashboard enum value: {0}{1}{2}.
        /// </summary>
        internal static string DeveloperDashboardCommands_SetException {
            get {
                return ResourceManager.GetString("DeveloperDashboardCommands_SetException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following exception has occured while trying to check in file &apos;{0}&apos;: {1}{2}{3}.
        /// </summary>
        internal static string FileSharePointCommands_CheckInException {
            get {
                return ResourceManager.GetString("FileSharePointCommands_CheckInException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following exception has occured while trying to check out file &apos;{0}&apos;: {1}{2}{3}.
        /// </summary>
        internal static string FileSharePointCommands_CheckOutException {
            get {
                return ResourceManager.GetString("FileSharePointCommands_CheckOutException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following exception has occured while trying to discard check out of file &apos;{0}&apos;: {1}{2}{3}.
        /// </summary>
        internal static string FileSharePointCommands_DiscardCheckOutException {
            get {
                return ResourceManager.GetString("FileSharePointCommands_DiscardCheckOutException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following exception has occured while trying to retrieve the file contents from &apos;{0}&apos;: {1}{2}{3}.
        /// </summary>
        internal static string FileSharePointCommands_GetContentsException {
            get {
                return ResourceManager.GetString("FileSharePointCommands_GetContentsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following exception has occured while trying to retrieve files: {0}{1}{2}.
        /// </summary>
        internal static string FileSharePointCommands_RetrieveFilesException {
            get {
                return ResourceManager.GetString("FileSharePointCommands_RetrieveFilesException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following exception has occured while trying to retrieve folders: {0}{1}{2}.
        /// </summary>
        internal static string FileSharePointCommands_RetrieveFoldersException {
            get {
                return ResourceManager.GetString("FileSharePointCommands_RetrieveFoldersException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following exception has occured while trying to save file contents to &apos;{0}&apos;: {1}{2}{3}.
        /// </summary>
        internal static string FileSharePointCommands_SaveException {
            get {
                return ResourceManager.GetString("FileSharePointCommands_SaveException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Pages and Page Layouts successfully retrieved.
        /// </summary>
        internal static string MasterPageGallerySharePointCommands_MasterPagesAndPageLayoutsSuccessfullyRetrieved {
            get {
                return ResourceManager.GetString("MasterPageGallerySharePointCommands_MasterPagesAndPageLayoutsSuccessfullyRetrieve" +
                        "d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following exception has occured while trying to retrieve Master Pages and Page Layouts: {0}{1}{2}.
        /// </summary>
        internal static string MasterPageGallerySharePointCommands_RetrievingException {
            get {
                return ResourceManager.GetString("MasterPageGallerySharePointCommands_RetrievingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to retrieve available Master Pages and Page Layouts....
        /// </summary>
        internal static string MasterPageGallerySharePointCommands_TryingToRetrieveAvailableMasterPagesAndPageLayouts {
            get {
                return ResourceManager.GetString("MasterPageGallerySharePointCommands_TryingToRetrieveAvailableMasterPagesAndPageLa" +
                        "youts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following exception has occured while trying to retrieve solutions: {0}{1}{2}.
        /// </summary>
        internal static string SolutionGallerySharePointCommands_RetrievingException {
            get {
                return ResourceManager.GetString("SolutionGallerySharePointCommands_RetrievingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to retrieve available solutions....
        /// </summary>
        internal static string SolutionGallerySharePointCommands_TryingToRetrieveAvailableSolutions {
            get {
                return ResourceManager.GetString("SolutionGallerySharePointCommands_TryingToRetrieveAvailableSolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following exception has occured while trying to retrieve themes: {0}{1}{2}.
        /// </summary>
        internal static string ThemeGallerySharePointCommands_RetrievingException {
            get {
                return ResourceManager.GetString("ThemeGallerySharePointCommands_RetrievingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to retrieve available themes....
        /// </summary>
        internal static string ThemeGallerySharePointCommands_TryingToRetrieveAvailableThemes {
            get {
                return ResourceManager.GetString("ThemeGallerySharePointCommands_TryingToRetrieveAvailableThemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following exception has occured while trying to retrieve web parts: {0}{1}{2}.
        /// </summary>
        internal static string WebPartGallerySharePointCommands_RetrievingException {
            get {
                return ResourceManager.GetString("WebPartGallerySharePointCommands_RetrievingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to retrieve available web parts....
        /// </summary>
        internal static string WebPartGallerySharePointCommands_TryingToRetrieveAvailableWebParts {
            get {
                return ResourceManager.GetString("WebPartGallerySharePointCommands_TryingToRetrieveAvailableWebParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web parts successfully retrieved.
        /// </summary>
        internal static string WebPartGallerySharePointCommands_WebPartsSuccessfullyRetrieved {
            get {
                return ResourceManager.GetString("WebPartGallerySharePointCommands_WebPartsSuccessfullyRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following exception has occured while trying to retrieve web template categories: {0}{1}{2}.
        /// </summary>
        internal static string WebTemplateSharePointCommands_CategoriesRetrievingException {
            get {
                return ResourceManager.GetString("WebTemplateSharePointCommands_CategoriesRetrievingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following exception has occured while trying to retrieve web templates: {0}{1}{2}.
        /// </summary>
        internal static string WebTemplateSharePointCommands_RetrievingException {
            get {
                return ResourceManager.GetString("WebTemplateSharePointCommands_RetrievingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to retrieve available web template categories....
        /// </summary>
        internal static string WebTemplateSharePointCommands_TryingToRetrieveAvailableCategories {
            get {
                return ResourceManager.GetString("WebTemplateSharePointCommands_TryingToRetrieveAvailableCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to retrieve available web templates....
        /// </summary>
        internal static string WebTemplateSharePointCommands_TryingToRetrieveAvailableWebTemplates {
            get {
                return ResourceManager.GetString("WebTemplateSharePointCommands_TryingToRetrieveAvailableWebTemplates", resourceCulture);
            }
        }
    }
}
